### ISSUE TITLE
Window Presentation

### ISSUE THREAD

**Issue by melyndaschreiber** [gjcooper/prespy#1]
Hello all, 

I am new to this presentation program. I am trying to implement this into python. I get the following error,

"RuntimeError: Error calling RunExperiment(): 
Presentation has lost full screen control of the stimulus display. This will happen when another window with the Windows focus overlaps at all with the stimulus display monitor. If you are unable to resolve this issue, consider using windowed presentation mode. See the Presentation documentation."

I'm not sure how to resolve this. I am currently running on a laptop with an external screen. Any thoughts?

Thanks, 

Melynda

**Comment by gjcooper** [comment]
Hi Melynda,

Sorry - never saw this when you posted it :disappointed:

I assume it has become apparent in the intervening time, but in case anyone else stumbles across this issue, my library (`prespy`) is only for reading Presentation:registered: log files into python and has no relationship to Presentation as a whole.

For help with an issue running an experiment in Presentation:registered: I recommend you go to their excellent forum system at https://www.neurobs.com/menu_support/menu_forums/contents_page

Gavin
